const SucculentAction = {
  GET_SUCCULENTS: 'GET_SUCCULENTS',
  GET_SUCCULENT_BY_ID: 'GET_SUCCULENT_BY_ID',
  CLOSE_OVERLAY: 'CLOSE_OVERLAY',
  GET_SUCCULENTS_SUCCESS: 'GET_SUCCULENTS_SUCCESS',
};

export {
  SucculentAction
};